kind: pipeline
type: docker
name: default

clone:
    disable: true

steps:
    - name: clone
      image: alpine/git
      commands:
          - git clone http://47.236.100.38:32768/godeye/godeye-frontend.git .
          - git checkout $DRONE_COMMIT

    - name: build_docker_image
      image: docker:rc-dind
      volumes:
          - name: docker-sock
            path: /var/run/docker.sock
      commands:
          - docker build -t godeye-frontend:latest .

    - name: deploy
      image: docker:rc-dind
      volumes:
          - name: docker-sock
            path: /var/run/docker.sock
      commands:
          - docker stop godeye-frontend || true
          - docker rm godeye-frontend || true
          - docker run -d --name godeye-frontend  -p 8000:8000 godeye-frontend:latest

volumes:
    - name: docker-sock
      host:
          path: /var/run/docker.sock
